@HttpContext.WebAPI_HostAddress = http://localhost:5064

GET http://localhost:5064/api/Values/Get/34/Taner
Accept: application/json
SecretKey: Taner Saydam

###


POST http://localhost:5064/api/Values/Create
Content-Type: application/json

{
  "email": "tanersaydam@gmail.com",
  "password": "1"
}